name: CI
on:
  push:
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala: ['2.11.12', '2.12.14', '2.13.6']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jdk-fx        
      - name: Setup SBT
        shell: bash
        run: |
          # update this only when sbt-the-bash-script needs to be updated
          export SBT_LAUNCHER=1.5.5
          export SBT_OPTS="-Dfile.encoding=UTF-8"
          curl -L --silent "https://github.com/sbt/sbt/releases/download/v$SBT_LAUNCHER/sbt-$SBT_LAUNCHER.tgz" > $HOME/sbt.tgz
          tar zxf $HOME/sbt.tgz -C $HOME
          sudo rm -f /usr/local/bin/sbt
          sudo ln -s $HOME/sbt/bin/sbt /usr/local/bin/sbt
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: Build and test
        run: sbt ++${{ matrix.scala }} clean test
